trigger: none

pool:
 vmImage: ubuntu-latest

stages:
  
  - stage: sastscanning
    jobs:
      - job: sastscan
        steps:
         - checkout: self
           fetchDepth: 0
         - task: SonarCloudPrepare@3
           inputs:
             SonarQube: 'sonar'
             organization: 'achintadutta04'
             scannerMode: 'cli'
             configMode: 'manual'
             cliProjectKey: 'achintadutta04_react-todo'
             cliProjectName: 'react-todo'
             cliSources: '.'
         - task: SonarCloudAnalyze@3
           inputs:
             jdkversion: 'JAVA_HOME_17_X64'
         - task: SonarCloudPublish@3
           inputs:
             pollingTimeoutSec: '300'
             
  - stage: build
    jobs:
      - job: buildJob
        steps:
        - task: Npm@1
          displayName: npm install run
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'

        - task: Npm@1
          displayName: npm run build running
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'run build'

        - task: PublishPipelineArtifact@1
          displayName: upload artifacts
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/build'
            artifact: 'todo-build'
            publishLocation: 'pipeline'

  

  - stage: deploy
    jobs:
      - job: deploymentJob
        steps:
        - task: DownloadBuildArtifacts@1
          continueOnError: true
          displayName: download artifacts
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'todo-build'
            downloadPath: '$(System.ArtifactsDirectory)'
            cleanDestinationFolder: true

        - task: CopyFilesOverSSH@0
          displayName: copying artifacts
          continueOnError: true
          inputs:
            sshEndpoint: 'app-connect'
            sourceFolder: '$(System.ArtifactsDirectory)'
            contents: '**'
            targetFolder: '/home/achinta/build'
            readyTimeout: '20000'

        - task: SSH@0
          displayName: copying file from /tmp to /html
          inputs:
            sshEndpoint: 'app-connect'
            runOptions: 'commands'
            commands: 'sudo cp -r /home/achinta/build/* /var/www/html'
            readyTimeout: '20000'